# === Gruvbox Dark ===

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.cursor]
text   = "#282828"
cursor = "#ebdbb2"

[colors.selection]
text       = "#ebdbb2"
background = "#3c3836"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[window]
opacity = 1.0

[window.padding]
x = 8
y = 12

